### ISSUE TITLE
Handle Discovery Catalog in Product Item Search

### ISSUE THREAD

**Issue by nickcoleman** [CruxConnect/crux-docs#123]
Update /products/item/search docs for issue #56  to handle specifying the catalog type by adding the following facet to the request:

catalog_type: [] or catalog_type not passed - returns the standard catalog as a default
catalog_type: [ standard ] - returns the standard catalog
catalog_type: [ discovery ] - returns the discovery catalog
catalog_type: [ standard, discovery ] - returns both standard and discovery catalogs

The chosen catalog_type facet shall be included in the response.  If no catalog_type was included in the request, the response shall include catalog_type: [ standard ].

We'll also continue to specify the supplier by including the supplier uuid in the supplier facet, 
ie. supplier[ supplier_uuid ]

ref issue #56 - Discovery Catalog
ref CruxConnect/crux-api#1082

**Comment by Gidgidonihah** [comment]
This should be added to PR #56

**Comment by nickcoleman** [comment]
Accomplished in pr #56
