### ISSUE TITLE
Complete the Discovery API Docs

### ISSUE THREAD

**Issue by Gidgidonihah** [CruxConnect/crux-docs#124]
All of the docs on PR #56 have been written by hand and are in no way represented in the original PAW file.

We need to:

- [x] Add each new endpoint (and any modified endpoints) to the master PAW files
- [x] Export and create the documentation from the PAW file
- [x] Get these changes merged into master

This can be done by either:
* Creating a new branch
  1. Branch off master
  1. Update your paw files
  1. Export new docs
  1. Create new PR
  1. Remove PR #56 and delete `discover-catalog`
* Use existing `discover-catalog` branch
  1. Merge master ensuring you have the most up to date PAW files
  1. Update your paw files
  1. Export new docs
  1. Remove `DO NOT MERGE` and `proposed change` labels

Then just get the PR reviewed and merged.

**Comment by nickcoleman** [comment]
- [ ] discovery/get_connections
- [ ] discovery/get_discovery_suppliers
- [ ] discovery/get_requested_connection_detail
- [ ] discovery/request_connection
- [ ] discovery/update_connection_request
- [ ] files/upload
- [ ] organization/get_connections
- [ ] tools/get_discovery_participation
- [ ] tools/update_discovery_participation
