### ISSUE TITLE
Create Flat Item SKU

### ISSUE THREAD

**Issue by nickcoleman** [CruxConnect/crux-docs#158]
This is an internal-internal (only used by the backend team) to import CSV formatted SKU files from our integration staff.  The CSV file is converted in to a flat JSON file which is then passed to this end-point.

Following is the current documented structure (which is out of date).   

---
name: product-create-or-update-flat
### URL

```
POST /products/flat-item-skus/
```

### Request

Accepts all fields described in "Product--thanos-import-format" as a single dict.

In general, if the field exists and an empty string or None is passed in, then
the value will be set to None (including any closely related information on
complex objects).  If the field is not present at all, then pre-existing data
will be preserved.

#### Successful new submission

```js
status: 201 Created
{ ... the sku and item data }
```

#### Successful update

```js
status: 200 OK
{ ... the sku and item data }
```

#### Salvaged create/update

Submissions with bad data may be salvaged if the bad data is not critical to
the submission or update.  In this case, the object is updated with the good
data and a warning is returned indicating exactly what happened.

```js
status: 202 Accepted
{
    "warnings": [
        {
            "type": 'AUTO_DROPPED_FIELDS' (potentially other types of warnings)
            "message": "Some fields contained bad data. Bad data was removed and remaining fields successfully submitted."
            "invalid_data": {
                'isbn': ["Invalid ISBN 'B0052P23YY': Only numbers allowed."],
                'asin': ["Invalid ASIN '182741000850': Wrong length", "Ensure this field has no more than 10 characters."]
            }
        }
    ]
    "updated_or_created": "updated"|"created"
    "accepted": {
        ... the accepted sku data
    }
}
```

#### Failed create/update

```
status: 400 Bad Request
{
    bad_data: {
        "critical": salvage_serializer.errors
        "non_critical": serializer.errors - salvage_serializer.errors
    }
}
```

**Comment by Gidgidonihah** [comment]
@nickcoleman Could you please indicate the issue for the backend changes this relies upon?

**Comment by Gidgidonihah** [comment]
@jtprince has said that it should be fine to close this issue. If/when further updates are made, a new issue will be created.
