### ISSUE TITLE
Prep Orders Ops Fulfillment Refactor

### ISSUE THREAD

**Issue by nickcoleman** [CruxConnect/crux-docs#179]
Issue #178 built the documentation to support a future release in support of the Orders Ops Fulfillment Refactor.

When the refactor is released, we'll need to move the docs built by #178 to the current docs.  Build examples of the request/response for each api.  And, refactor the  _config.yml an _includes/filtered_collections.html files to remove the future release.

**Comment by Gidgidonihah** [comment]
Superceded by #182
