### ISSUE TITLE
Supplier Tracking File Spec Update

### ISSUE THREAD

**Issue by nickcoleman** [CruxConnect/crux-docs#210]
Ref:  crux-docs/_fs_order_data/tracking.md

Update the referenced tracking document and the associated sample file to include the "package_attributes" field:

package_attributes: (array) Supplier provided array of key/value package attribute objects

Package Attribute object:
   "attribute_name": "package level attribute name",
   "attribute_value": "package level attribute value"

in the supplier file, the package attributes are flattened and separated by ;;
For example:
   "shipping weight":10;;"width":2

**Comment by koltonev** [comment]
Updated documentation and files with `package_attributes` field.

https://github.com/CruxConnect/crux-docs/pull/211
