### ISSUE TITLE
Update Order Fees path incorrect

### ISSUE THREAD

**Issue by nickcoleman** [CruxConnect/crux-docs#212]
Ref: [orders/update_order_fees.md](https://github.com/CruxConnect/crux-docs/blob/master/_order/update_order_fees.md)

Change the Update Order Fees path 
    POST /timp/orders/<order_uuid>/
to:
    POST /timp/orders/<order_uuid>/fees/

**Comment by koltonev** [comment]
API Docs show `/timp/orders/&lt;order_uuid&gt;/fees/`
