### ISSUE TITLE
Allocation file includes `supplier_provided_shipping_cost`

### ISSUE THREAD

**Issue by Gidgidonihah** [CruxConnect/crux-docs#215]
The allocation file should not have `supplier_provided_shipping_cost`. There is nothing we can do with that upon allocation. That is currently invoice-level data.

**Comment by Gidgidonihah** [comment]
Same note for tracking.

**Comment by Gidgidonihah** [comment]
The references have been removed from the docs on the branch `remove-supplier_provided_shipping_cost-215`, but they still need to be removed from the sample files.

**Comment by koltonev** [comment]
https://github.com/CruxConnect/crux-docs/commit/2b399c1c21553394b2353b9549f917f9a24648ea
