### ISSUE TITLE
Organize supplier/retailer endpoints

### ISSUE THREAD

**Issue by Gidgidonihah** [CruxConnect/crux-docs#73]
In the product grouping specifically it seems that the endpoints would be better organized by account type:

* Product (Universal)
* Product (Retailer)
* Product (Supplier)

Would this also apply to other sections at all?

**Comment by nickcoleman** [comment]
Review each and separate as supplier or retailer as appropriate:

- [ ] Accounting
- [ ] Organization
- [ ] Product
- [ ] Orders
- [ ] Discovery
- [ ] Tools
- [ ] Files
- [ ] Data
