### ISSUE TITLE
Cleanup branches

### ISSUE THREAD

**Issue by Gidgidonihah** [CruxConnect/crux-docs#96]
There are a [handful of branches](https://github.com/CruxConnect/crux-api-docs/branches) that are 'stale' or haven't been updated in a couple months.

With anything that was last updated more than 2 months ago should we should check what the changes were and incorporate them are discard them as it makes sense.

# Branches
## `thanos-export`
The only change for thanos-export is the addition of the `Product--CREATE-OR-UPDATE-flat-item-sku.md` file. This seems like general documentation that can be cleaned up and added to the general documentation (or perhaps products) section.

## `SupplierOrderIntegration`
The only change for this branch is the addition of the `Order--SupplierOrders.md` file. Let's make sure that the endpoint is documented and up to date, then delete this branch.

## `add_phone_retailer`
Seems to be (as described by the name) the addition of phone to the `create_order_retailer.md`, `get_order_detail.md` calls.
Also includes the addition of the `_ordering/get_order_list.md (/api/orders/)` call.

**Comment by nickcoleman** [comment]
- [ ] thanos-export
- [ ] gollum-docs (Jason)
- [ ] file-specs (Konan)
- [ ] 125-order-docs
